table DimChannel
	lineageTag: 4789fd53-490b-4eba-8d84-7627f7faea8e

	column ChannelKey
		dataType: int64
		formatString: 0
		lineageTag: 9a1ad9ab-a33b-4977-adef-cc03d37b0d34
		summarizeBy: none
		sourceColumn: ChannelKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ChannelName
		dataType: string
		lineageTag: 0069fe9d-f7f2-4d45-b594-f7fa977e0ec6
		summarizeBy: none
		sourceColumn: ChannelName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition DimChannel = m
		mode: import
		source =
				let
				    Origen = Folder.Files(#"Directorio datos"),
				    #"_DimChannel xlsx" = Origen{[#"Folder Path"=#"Directorio datos",Name="DimChannel.xlsx"]}[Content],
				    #"Libro de Excel importado" = Excel.Workbook(#"_DimChannel xlsx"),
				    DimChannel_Sheet = #"Libro de Excel importado"{[Item="DimChannel",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(DimChannel_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"ChannelKey", Int64.Type}, {"ChannelName", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

